### ISSUE TITLE
Cant build for 5.1

### ISSUE THREAD

**Issue by fake-fakers** [cem-akkaya/LightAwareness#2]
Hello.
Tryed to build project with plugin here Drive:\UE\Engine\Plugins\Marketplace\LightAwareness
And i get this - Microsoft.MakeFile.targets(44, 5): [MSB3073]  blah blah with code 6.

Then i tried to place plugin in project files.
And i get this -   LightAwarenessComponent.h(17): [] Regular enums only support 'int' as the value size
So i changed it to just "int" and get successfull build, but then in editor i got another error

![image](https://github.com/cem-akkaya/LightAwareness/assets/28289317/cd3bf066-3e2a-4fb1-9b4d-ee35379541e9)
![image](https://github.com/cem-akkaya/LightAwareness/assets/28289317/4188d68c-1d3a-4a05-b3a0-0c8bdb621a9f)

p.s. i dont know what am i doing at all.

**Comment by fake-fakers** [comment]
oh shit, scenecapture2d doesn't really capture point lights in 5.1, so it's all meanless

**Comment by cem-akkaya** [comment]
I am making a workaround for you, that will be working in 5.1

**Comment by cem-akkaya** [comment]
Hello,

I made some updates here and there, details are [here](https://github.com/cem-akkaya/LightAwareness/commit/904e516d369d812fad9af6180b1dc6c110a77eef).

Please download the new version and rebuild your project.

However you should be able to integrate this under your game plugins 5.1, I just tested without any errors just to be sure.
- you shouldn't be seeing any enum errors.
- you shoudln't be seeing any asset loading errors. Assets should be loaded under Plugings/LightAwareness/Content
- you shouldn't be sseing any engine version errors.

On component there is a new option names "Engine Version Fallback" make it true and it should be working as expected.

However an engine version update is recommended if you are building a game/project solely depending on this, 5.3 and up versions would be working more accurately due to changes in engine code.

Let me know if you can get it work.

Cem

ps: no one really does know.

**Comment by fake-fakers** [comment]
Thank you! Ive just encountered strange behavior like its mirrored or something, but idk maybe i messed up something in widgets. Doesn't matter anyway because i just needed that float)

![image](https://github.com/cem-akkaya/LightAwareness/assets/28289317/8710588a-b45e-42b5-a163-ad850fa14574)

Thank you again, brilliant idea with all that 16х16 capture/render/pixels stuff.

p.s. sorry for bad english
